### ISSUE TITLE
Free the name Git.jl for GitCommand.jl

### ISSUE THREAD

**Issue by crstnbr** [JuliaVersionControl/Git.jl#25]
Now that we have the great [GitCommand.jl](https://github.com/bcbi/GitCommand.jl) I suggest that we rename this package to something else and make GitCommand.jl the new Git.jl. ([came up on discourse](https://discourse.julialang.org/t/ann-gitcommand-jl-use-command-line-git-in-your-julia-packages/32330/4))

As far as I understand, this package mainly bundles legacy code from Base that was thought to be useful to be kept around in a package. It is barely maintained - my PR from over a year ago was the last to be merged - has no documentation, and is IMHO somewhat akward to use.

GitCommand.jl on the other hand

* installs git via [Git_jll.jl](https://github.com/JuliaBinaryWrappers/Git_jll.jl)
* provides a clean git interface
* adds a git REPL mode, etc.

I suspect that users searching for how to access git functionality in Julia would always want GitCommand.jl instead of this package, despite the premium name. I suggest we change the names to reflect this.

What do you guys think, @dilumaluthge, @ararslan, @StefanKarpinski?

PS: Perhaps we could alternatively have two Git.jl's with different UUIDs. But I don't even know how selecting which package to work with/install works in such a scenario. And frankly, I think that the code in this package isn't worth the trouble (please correct me if I'm wrong).

**Comment by DilumAluthge** [comment]
I’d support it.

The problem is that I don’t want to delete packages from General.

Perhaps we could do the same trick we did for PackageCompiler/PackageCompilerX? @kristofferc

**Comment by DilumAluthge** [comment]
> PS: Perhaps we could alternatively have two Git.jl's with different UUIDs. But I don't even know how selecting which package to work with/install works in such a scenario. And frankly, I think that the code in this package isn't worth the trouble (please correct me if I'm wrong).

Yeah let’s try to avoid this situation.

**Comment by DilumAluthge** [comment]
> Perhaps we could do the same trick we did for PackageCompiler/PackageCompilerX? @KristofferC

To elaborate for those that aren’t familiar. We would make a pull request to this repo that deletes all the existing content and replaces it with the content of GitCommand.jl. Then we would make a breaking release of Git.jl. We would archive GitCommand.jl and add a link redirecting them to this repo.
