### ISSUE TITLE
Support interpolating in git cmd string macro

### ISSUE THREAD

**Issue by fredrikekre** [JuliaVersionControl/Git.jl#30]

**Comment by GunnarFarneback** [comment]
I propose to deprecate the cmd string macro in favor of `git("clone https://github.com/JuliaRegistries/General")` and split the argument with `Base.shell_split`. This gives interpolation for free and allows the use of whatever string macros people want to use. (I already have a PR in preparation for `git(::AbstractString)`).

**Comment by fredrikekre** [comment]
Isn't it better to just let people use
```
git = Git.git()
`$git clone ....`
```
?

**Comment by GunnarFarneback** [comment]
That's already available so if we think that's all that's needed the easiest solution is just to remove the cmd macro.

**Comment by fredrikekre** [comment]
Exactly. Is there any other advantage with the cmd macro?

**Comment by GunnarFarneback** [comment]
Considering that it currently does a plain `split` of the argument I would say that it's mostly kinda dangerous but for one time uses it's a bit more compact than first having to create the `git` object or interpolating it into the command. My proposal would allow things like `git(raw"status src\foo\bar.jl")` which might be practical if you e.g. need to copy/paste paths on Windows.

The functionality I really want, however, is `git(["status", "README.md"])` to bypass the cmd argument parsing. But maybe the magic of the cmd interpolation of iterables doesn't make it worth the trouble.

**Comment by DilumAluthge** [comment]
It sounds like the plan here would be:
1. Remove the `@git_cmd` cmd macro. We can do this in a nonbreaking release because it's not part of the public API.
2. Add a new method `git(::AbstractVector(<:AbstractString))` for the use case that @GunnarFarneback wants.

**Comment by DilumAluthge** [comment]
Step 1 is done in #34
