### ISSUE TITLE
Git package not self-sufficient on Windows

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaVersionControl/Git.jl#50]
As noted in e.g. https://github.com/JuliaVersionControl/Git.jl/issues/40#issuecomment-1144307266, some git commands are implemented as shell scripts, e.g. `git submodule` and some of the commands in the [SIP workaround testset](https://github.com/JuliaVersionControl/Git.jl/blob/259dc047e11ee326b7d2cac63cb09ceeb8f4711b/test/runtests.jl#L50-L72).

This means that git will try to spawn `sh`, which it expects to be installed as part of `git bash`. If you have an external `git` installation and have configured it to put `git bash` in `PATH`, this works also from `Git_jll` but if you have not, or don't have an external git installation at all, you are [out of luck](https://github.com/GunnarFarneback/LocalRegistry.jl/issues/76#issuecomment-1815386482).

This is most easily diagnosed by trying to run the `Git` package tests, which will fail in the `SIP workaround` testset if `git bash` is not available in `PATH`.

**Comment by GunnarFarneback** [comment]
I made the experiment to replace the contents of the current artifact (a799966f2a26ba3df00abcd7331bf9c2ef282c54) with the full contents of https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.tar.bz2 and it just worked, at least to the extent that both the `Git` and `LocalRegistry#git_jll` packages passed their tests.

Thus I propose that the next time there is a new Git release available, in addition to bumping the version, we apply the following patch to Yggdrasil:
```
diff --git a/G/Git/build_tarballs.jl b/G/Git/build_tarballs.jl
index d6223d5b..105fb7dc 100644
--- a/G/Git/build_tarballs.jl
+++ b/G/Git/build_tarballs.jl
@@ -21,7 +21,7 @@ install_license ${WORKSPACE}/srcdir/git-*/COPYING
 
 if [[ "${target}" == *-ming* ]]; then
     # Fast path for Windows: just copy the content of the tarball to the prefix
-    cp -r ${WORKSPACE}/srcdir/${target}/mingw${nbits}/* ${prefix}
+    cp -r ${WORKSPACE}/srcdir/${target}/* ${prefix}
     exit
 fi
```

Effectively this change means that also `git bash` is included in `Git_jll`, so that all git commands work without an external `git bash` installation.

Cc. @eschnett and @palday, who made the last two Git updates in Yggdrasil, to see that it doesn't interfere with your usage of `Git_jll` or if you have any other feedback.

For the `Git` package we should probably make a new release which lower-bounds `Git_jll` to the new version, but otherwise I don't think anything else needs to be done.

**Comment by palday** [comment]
@GunnarFarneback I'm not using Windows for anything and I don't remember why I needed to bump the git binary version previously, so I don't think this will impact me. I agree that exposing Git also means exposing the stuff written in bash.
